version: "3.9"

services:
  redis-docker:
    restart: unless-stopped
    build: .
    stdin_open: true
    tty: true
    volumes:
        - .:/redis
    container_name: redis
    network_mode: host
    healthcheck:
        test: [ "CMD", "redis-cli", "ping" ]
        interval: 1s
        timeout: 3s
        retries: 30